import type { CurrentUser, LeaderboardUser, Question, TriviaFact, CategoryMeta } from "@/lib/types";

export const questions: Question[] = [
  {
    id: "q1",
    category: "Science",
    difficulty: "Easy",
    question: "What is the chemical symbol for gold?",
    options: ["Go", "Gd", "Au", "Ag"],
    correctAnswer: "Au",
    explanation: "Gold's symbol is Au from the Latin word aurum.",
  },
  {
    id: "q2",
    category: "Science",
    difficulty: "Medium",
    question: "How many bones does an adult human typically have?",
    options: ["198", "206", "212", "220"],
    correctAnswer: "206",
    explanation: "An adult skeleton usually contains 206 bones.",
  },
  {
    id: "q3",
    category: "Science",
    difficulty: "Hard",
    question: "Which planet has the most moons currently confirmed?",
    options: ["Jupiter", "Saturn", "Uranus", "Neptune"],
    correctAnswer: "Saturn",
    explanation: "Saturn currently leads with the highest number of confirmed moons.",
  },
  {
    id: "q4",
    category: "History",
    difficulty: "Easy",
    question: "In what year did World War II end?",
    options: ["1944", "1945", "1946", "1939"],
    correctAnswer: "1945",
    explanation: "WWII ended in 1945.",
  },
  {
    id: "q5",
    category: "History",
    difficulty: "Medium",
    question: "Which empire built Machu Picchu?",
    options: ["Maya", "Aztec", "Inca", "Roman"],
    correctAnswer: "Inca",
    explanation: "Machu Picchu was built by the Inca civilization.",
  },
  {
    id: "q6",
    category: "History",
    difficulty: "Hard",
    question: "Who signed the Magna Carta in 1215?",
    options: ["Henry VIII", "Richard I", "John of England", "Edward I"],
    correctAnswer: "John of England",
    explanation: "King John of England agreed to the Magna Carta.",
  },
  {
    id: "q7",
    category: "Tech",
    difficulty: "Easy",
    question: "What does CPU stand for?",
    options: ["Central Process Unit", "Central Processing Unit", "Computer Personal Unit", "Core Processing Utility"],
    correctAnswer: "Central Processing Unit",
    explanation: "CPU means Central Processing Unit.",
  },
  {
    id: "q8",
    category: "Tech",
    difficulty: "Medium",
    question: "Which language is primarily used for styling web pages?",
    options: ["CSS", "Python", "Rust", "SQL"],
    correctAnswer: "CSS",
    explanation: "CSS is used for describing the presentation of web pages.",
  },
  {
    id: "q9",
    category: "Tech",
    difficulty: "Hard",
    question: "What data structure does a browser's back button emulate?",
    options: ["Queue", "Heap", "Stack", "Graph"],
    correctAnswer: "Stack",
    explanation: "Navigation history behaves like a stack (LIFO).",
  },
  {
    id: "q10",
    category: "Nature",
    difficulty: "Easy",
    question: "Which gas do plants absorb from the atmosphere?",
    options: ["Oxygen", "Hydrogen", "Carbon Dioxide", "Nitrogen"],
    correctAnswer: "Carbon Dioxide",
    explanation: "Plants use carbon dioxide in photosynthesis.",
  },
  {
    id: "q11",
    category: "Nature",
    difficulty: "Medium",
    question: "What is the largest ocean on Earth?",
    options: ["Atlantic", "Indian", "Pacific", "Arctic"],
    correctAnswer: "Pacific",
    explanation: "The Pacific Ocean is the largest and deepest ocean.",
  },
  {
    id: "q12",
    category: "Nature",
    difficulty: "Hard",
    question: "What is the fastest land animal?",
    options: ["Cheetah", "Pronghorn", "Lion", "Greyhound"],
    correctAnswer: "Cheetah",
    explanation: "Cheetahs can sprint up to around 70 mph.",
  },
  {
    id: "q13",
    category: "Arts",
    difficulty: "Easy",
    question: "Who painted the Mona Lisa?",
    options: ["Van Gogh", "Michelangelo", "Da Vinci", "Picasso"],
    correctAnswer: "Da Vinci",
    explanation: "Leonardo da Vinci painted the Mona Lisa.",
  },
  {
    id: "q14",
    category: "Arts",
    difficulty: "Medium",
    question: "What musical symbol indicates silence?",
    options: ["Clef", "Rest", "Sharp", "Slur"],
    correctAnswer: "Rest",
    explanation: "A rest indicates silence for a defined duration.",
  },
  {
    id: "q15",
    category: "Arts",
    difficulty: "Hard",
    question: "Which architect designed the Guggenheim Museum in Bilbao?",
    options: ["Frank Gehry", "Zaha Hadid", "Norman Foster", "I. M. Pei"],
    correctAnswer: "Frank Gehry",
    explanation: "Frank Gehry designed the Guggenheim Museum Bilbao.",
  },
  {
    id: "q16",
    category: "Science",
    difficulty: "Easy",
    question: "What is H2O commonly known as?",
    options: ["Oxygen", "Hydrogen", "Water", "Salt"],
    correctAnswer: "Water",
    explanation: "H2O is water.",
  },
  {
    id: "q17",
    category: "History",
    difficulty: "Medium",
    question: "The Renaissance began in which country?",
    options: ["France", "Italy", "Germany", "Spain"],
    correctAnswer: "Italy",
    explanation: "The Renaissance started in Italy in the 14th century.",
  },
  {
    id: "q18",
    category: "Tech",
    difficulty: "Hard",
    question: "Which protocol secures data over the web using certificates?",
    options: ["FTP", "HTTP", "HTTPS", "SMTP"],
    correctAnswer: "HTTPS",
    explanation: "HTTPS uses TLS certificates for secure connections.",
  },
  {
    id: "q19",
    category: "Nature",
    difficulty: "Medium",
    question: "Which layer protects Earth from harmful UV rays?",
    options: ["Troposphere", "Mesosphere", "Ozone Layer", "Ionosphere"],
    correctAnswer: "Ozone Layer",
    explanation: "The ozone layer in the stratosphere absorbs most UV radiation.",
  },
  {
    id: "q20",
    category: "Arts",
    difficulty: "Easy",
    question: "How many strings does a violin have?",
    options: ["4", "5", "6", "7"],
    correctAnswer: "4",
    explanation: "A standard violin has four strings.",
  },
  {
    id: "q21",
    category: "Science",
    difficulty: "Hard",
    question: "What is the unit of electrical resistance?",
    options: ["Volt", "Ampere", "Ohm", "Watt"],
    correctAnswer: "Ohm",
    explanation: "Resistance is measured in ohms.",
  },
  {
    id: "q22",
    category: "History",
    difficulty: "Hard",
    question: "Which treaty ended World War I?",
    options: ["Treaty of Paris", "Treaty of Versailles", "Treaty of Ghent", "Treaty of Tordesillas"],
    correctAnswer: "Treaty of Versailles",
    explanation: "WWI officially ended with the Treaty of Versailles in 1919.",
  },
  {
    id: "q23",
    category: "Tech",
    difficulty: "Medium",
    question: "Git is primarily used for what?",
    options: ["Image editing", "Version control", "Database backup", "Web hosting"],
    correctAnswer: "Version control",
    explanation: "Git tracks changes to source code over time.",
  },
  {
    id: "q24",
    category: "Nature",
    difficulty: "Hard",
    question: "Which desert is the largest hot desert?",
    options: ["Gobi", "Sahara", "Arabian", "Kalahari"],
    correctAnswer: "Sahara",
    explanation: "The Sahara is the largest hot desert in the world.",
  },
  {
    id: "q25",
    category: "Arts",
    difficulty: "Medium",
    question: "Which dance originated in Argentina and Uruguay?",
    options: ["Salsa", "Flamenco", "Tango", "Waltz"],
    correctAnswer: "Tango",
    explanation: "Tango began in the Rio de la Plata region.",
  },
  {
    id: "q26",
    category: "Science",
    difficulty: "Medium",
    question: "Which blood type is known as the universal donor?",
    options: ["O negative", "AB positive", "A positive", "B negative"],
    correctAnswer: "O negative",
    explanation: "O negative red blood cells can be transfused to most recipients.",
  },
  {
    id: "q27",
    category: "History",
    difficulty: "Easy",
    question: "Who was the first President of the United States?",
    options: ["Thomas Jefferson", "George Washington", "John Adams", "James Madison"],
    correctAnswer: "George Washington",
    explanation: "George Washington served as the first U.S. President.",
  },
  {
    id: "q28",
    category: "Tech",
    difficulty: "Easy",
    question: "What does RAM stand for?",
    options: ["Read Access Memory", "Random Access Memory", "Rapid Access Module", "Realtime Active Memory"],
    correctAnswer: "Random Access Memory",
    explanation: "RAM stands for Random Access Memory.",
  },
  {
    id: "q29",
    category: "Nature",
    difficulty: "Easy",
    question: "How many continents are there?",
    options: ["5", "6", "7", "8"],
    correctAnswer: "7",
    explanation: "There are seven continents on Earth.",
  },
  {
    id: "q30",
    category: "Arts",
    difficulty: "Hard",
    question: "Which filmmaker directed 'Spirited Away'?",
    options: ["Akira Kurosawa", "Hayao Miyazaki", "Makoto Shinkai", "Mamoru Hosoda"],
    correctAnswer: "Hayao Miyazaki",
    explanation: "Hayao Miyazaki wrote and directed Spirited Away.",
  },
  {
    id: "q31",
    category: "Anime",
    difficulty: "Easy",
    question: "Which anime features the character Naruto Uzumaki?",
    options: ["Bleach", "Naruto", "One Piece", "Attack on Titan"],
    correctAnswer: "Naruto",
    explanation: "Naruto Uzumaki is the main character of Naruto.",
  },
  {
    id: "q32",
    category: "Anime",
    difficulty: "Medium",
    question: "Studio Ghibli is based in which country?",
    options: ["Japan", "South Korea", "France", "Canada"],
    correctAnswer: "Japan",
    explanation: "Studio Ghibli is a Japanese animation studio.",
  },
  {
    id: "q33",
    category: "Anime",
    difficulty: "Hard",
    question: "What is the name of the titan that Eren Yeager can transform into?",
    options: ["Colossal Titan", "Armored Titan", "Attack Titan", "Jaw Titan"],
    correctAnswer: "Attack Titan",
    explanation: "Eren Yeager inherits the Attack Titan.",
  },
  {
    id: "q34",
    category: "Food",
    difficulty: "Easy",
    question: "What fruit is commonly used to make guacamole?",
    options: ["Mango", "Avocado", "Banana", "Apple"],
    correctAnswer: "Avocado",
    explanation: "Guacamole is primarily made from avocados.",
  },
  {
    id: "q35",
    category: "Food",
    difficulty: "Medium",
    question: "Sushi is most closely associated with which country?",
    options: ["Japan", "Italy", "Mexico", "Thailand"],
    correctAnswer: "Japan",
    explanation: "Sushi is a traditional Japanese dish.",
  },
  {
    id: "q36",
    category: "Food",
    difficulty: "Hard",
    question: "Which spice gives curry powder its bright yellow color?",
    options: ["Paprika", "Turmeric", "Cumin", "Cinnamon"],
    correctAnswer: "Turmeric",
    explanation: "Turmeric is responsible for curry powder's yellow hue.",
  },
  {
    id: "q37",
    category: "Animals",
    difficulty: "Easy",
    question: "What is a baby cat called?",
    options: ["Puppy", "Kitten", "Cub", "Foal"],
    correctAnswer: "Kitten",
    explanation: "A young cat is called a kitten.",
  },
  {
    id: "q38",
    category: "Animals",
    difficulty: "Medium",
    question: "Which animal is known for its black-and-white stripes?",
    options: ["Giraffe", "Zebra", "Penguin", "Panda"],
    correctAnswer: "Zebra",
    explanation: "Zebras are famous for their striped coats.",
  },
  {
    id: "q39",
    category: "Animals",
    difficulty: "Hard",
    question: "What mammal can fly?",
    options: ["Flying squirrel", "Bat", "Sugar glider", "Colugo"],
    correctAnswer: "Bat",
    explanation: "Bats are the only mammals capable of true flight.",
  },
  {
    id: "q40",
    category: "Business",
    difficulty: "Easy",
    question: "What do you call the money a company earns after expenses?",
    options: ["Revenue", "Profit", "Debt", "Tax"],
    correctAnswer: "Profit",
    explanation: "Profit is the money left after subtracting expenses from revenue.",
  },
  {
    id: "q41",
    category: "Business",
    difficulty: "Medium",
    question: "A company's ownership divided into shares is called what?",
    options: ["Equity", "Liquidity", "Inventory", "Liability"],
    correctAnswer: "Equity",
    explanation: "Equity represents ownership value in a business.",
  },
  {
    id: "q42",
    category: "Business",
    difficulty: "Hard",
    question: "What does IPO stand for?",
    options: ["Initial Public Offering", "Internal Price Order", "Indexed Profit Option", "International Purchase Offer"],
    correctAnswer: "Initial Public Offering",
    explanation: "An IPO is when a company sells shares to the public for the first time.",
  },
];

export const triviaFacts: TriviaFact[] = [
  { id: "f1", category: "Science", title: "Bananas Are Radioactive", body: "Bananas contain potassium-40, a naturally occurring radioactive isotope. The dose is tiny and harmless.", likes: 128 },
  { id: "f2", category: "History", title: "Shortest War", body: "The Anglo-Zanzibar War of 1896 lasted around 38 to 45 minutes.", likes: 201 },
  { id: "f3", category: "Tech", title: "First Computer Bug", body: "In 1947, engineers found an actual moth in a relay of the Harvard Mark II.", likes: 330 },
  { id: "f4", category: "Nature", title: "Trees Communicate", body: "Trees can share nutrients and chemical signals through fungal networks in soil.", likes: 276 },
  { id: "f5", category: "Arts", title: "Longest-Running Play", body: "The Mousetrap by Agatha Christie has been staged continuously in London since 1952.", likes: 182 },
  { id: "f6", category: "Science", title: "Octopus Hearts", body: "An octopus has three hearts and blue blood due to copper-rich hemocyanin.", likes: 419 },
  { id: "f7", category: "History", title: "Library of Ashurbanipal", body: "One of the earliest known libraries was built in ancient Nineveh around the 7th century BCE.", likes: 173 },
  { id: "f8", category: "Tech", title: "Email Predates Web", body: "Email existed before the World Wide Web and was widely used on ARPANET.", likes: 144 },
  { id: "f9", category: "Nature", title: "Tardigrade Survival", body: "Tardigrades can survive extreme heat, cold, and even the vacuum of space.", likes: 388 },
  { id: "f10", category: "Arts", title: "Color Film Milestone", body: "Technicolor transformed Hollywood visuals in the 1930s and 1940s.", likes: 113 },
  { id: "f11", category: "Science", title: "Neutron Star Density", body: "A teaspoon of neutron star material would weigh billions of tons on Earth.", likes: 501 },
  { id: "f12", category: "History", title: "Roman Concrete", body: "Roman marine concrete can become stronger over time due to seawater reactions.", likes: 257 },
  { id: "f13", category: "Tech", title: "First Webcam", body: "The first webcam monitored a coffee pot at Cambridge University in 1991.", likes: 193 },
  { id: "f14", category: "Nature", title: "Shark Age", body: "Sharks existed before trees appeared on Earth.", likes: 462 },
  { id: "f15", category: "Arts", title: "Piano Key Count", body: "A modern piano typically has 88 keys: 52 white and 36 black.", likes: 156 },
];

const baseUsers: Omit<LeaderboardUser, "rank">[] = [
  { id: "u1", username: "NovaByte", avatar: "NB", score: 16840, accuracy: 94, quizCount: 302, tier: "Legendary" },
  { id: "u2", username: "EchoDrift", avatar: "ED", score: 16220, accuracy: 91, quizCount: 288, tier: "Legendary" },
  { id: "u3", username: "AtlasIQ", avatar: "AI", score: 15790, accuracy: 90, quizCount: 265, tier: "Expert" },
  { id: "u4", username: "PixelSage", avatar: "PS", score: 15120, accuracy: 89, quizCount: 247, tier: "Expert" },
  { id: "u5", username: "LunaLogic", avatar: "LL", score: 14820, accuracy: 88, quizCount: 251, tier: "Expert" },
  { id: "u6", username: "CipherRay", avatar: "CR", score: 14030, accuracy: 86, quizCount: 230, tier: "Pro" },
  { id: "u7", username: "QuantumPanda", avatar: "QP", score: 13680, accuracy: 87, quizCount: 221, tier: "Pro" },
  { id: "u8", username: "RogueNeuron", avatar: "RN", score: 13220, accuracy: 84, quizCount: 218, tier: "Pro" },
  { id: "u9", username: "ZenithFox", avatar: "ZF", score: 12810, accuracy: 83, quizCount: 207, tier: "Pro" },
  { id: "u10", username: "OrbitMuse", avatar: "OM", score: 12440, accuracy: 82, quizCount: 197, tier: "Pro" },
  { id: "u11", username: "TriviaTide", avatar: "TT", score: 11990, accuracy: 81, quizCount: 190, tier: "Rising" },
  { id: "u12", username: "CobaltSpark", avatar: "CS", score: 11650, accuracy: 80, quizCount: 188, tier: "Rising" },
  { id: "u13", username: "MythicLoop", avatar: "ML", score: 11220, accuracy: 79, quizCount: 175, tier: "Rising" },
  { id: "u14", username: "DataRaven", avatar: "DR", score: 10890, accuracy: 78, quizCount: 172, tier: "Rising" },
  { id: "u15", username: "ArgoMind", avatar: "AM", score: 10630, accuracy: 77, quizCount: 165, tier: "Rising" },
  { id: "u16", username: "CometAce", avatar: "CA", score: 10340, accuracy: 76, quizCount: 162, tier: "Rising" },
  { id: "u17", username: "SonicGlyph", avatar: "SG", score: 10010, accuracy: 76, quizCount: 150, tier: "Rising" },
  { id: "u18", username: "NebulaNerd", avatar: "NN", score: 9780, accuracy: 74, quizCount: 146, tier: "Rising" },
  { id: "u19", username: "HyperQuill", avatar: "HQ", score: 9520, accuracy: 74, quizCount: 141, tier: "Rising" },
  { id: "u20", username: "VoltNomad", avatar: "VN", score: 9340, accuracy: 73, quizCount: 137, tier: "Rising" },
];

export const leaderboardUsers: LeaderboardUser[] = baseUsers
  .sort((a, b) => b.score - a.score)
  .map((user, index) => ({ ...user, rank: index + 1 }));

export const currentUser: CurrentUser = {
  id: "me",
  username: "ArcShift",
  avatar: "AS",
  score: 14580,
  accuracy: 87,
  quizCount: 236,
  rank: 6,
  tier: "Expert",
  handle: "@arcshift",
  joinDate: "Joined Mar 2024",
  streak: 12,
  points: 27440,
  weeklyGoal: 74,
  badges: ["Speedster", "Streak x10", "Science Buff", "Battle Champ"],
  savedFactIds: ["f3", "f6", "f11"],
  quizHistory: [
    { id: "h1", category: "Science", name: "Solar System Sprint", date: "Apr 5, 2026", score: "9/10" },
    { id: "h2", category: "History", name: "Empire Clash", date: "Apr 4, 2026", score: "8/10" },
    { id: "h3", category: "Tech", name: "Web Dev Gauntlet", date: "Apr 3, 2026", score: "10/10" },
    { id: "h4", category: "Arts", name: "Canvas & Cinema", date: "Apr 1, 2026", score: "7/10" },
  ],
};

export const categoryMeta: CategoryMeta[] = [
  {
    name: "Science",
    iconName: "flask",
    color: "#22C55E",
    difficulty: "Easy",
    questionCount: questions.filter((q) => q.category === "Science").length,
  },
  {
    name: "History",
    iconName: "landmark",
    color: "#F59E0B",
    difficulty: "Medium",
    questionCount: questions.filter((q) => q.category === "History").length,
  },
  {
    name: "Tech",
    iconName: "microchip",
    color: "#3B82F6",
    difficulty: "Hard",
    questionCount: questions.filter((q) => q.category === "Tech").length,
  },
  {
    name: "Nature",
    iconName: "leaf",
    color: "#14B8A6",
    difficulty: "Medium",
    questionCount: questions.filter((q) => q.category === "Nature").length,
  },
  {
    name: "Anime",
    iconName: "clapperboard",
    color: "#0EA5E9",
    difficulty: "Medium",
    questionCount: questions.filter((q) => q.category === "Anime").length,
  },
  {
    name: "Food",
    iconName: "utensils",
    color: "#F97316",
    difficulty: "Easy",
    questionCount: questions.filter((q) => q.category === "Food").length,
  },
  {
    name: "Animals",
    iconName: "paw",
    color: "#8B5CF6",
    difficulty: "Hard",
    questionCount: questions.filter((q) => q.category === "Animals").length,
  },
  {
    name: "Business",
    iconName: "briefcase",
    color: "#EF4444",
    difficulty: "Medium",
    questionCount: questions.filter((q) => q.category === "Business").length,
  },
];

export const onlinePlayers = 1248;
