export type TrueFalseQuestionCount = 10 | 15 | 20 | 25 | 30;

export interface TrueFalseBankEntry {
  statement: string;
  answer: boolean;
}

export interface PreparedTrueFalseQuestion {
  question: string;
  options: string[];
  correctAnswer: string;
}

export const trueFalseQuestionBank: Record<string, Partial<Record<TrueFalseQuestionCount, TrueFalseBankEntry[]>>> = {
  "Animals": {
    10: [
      { statement: "Elephants are the largest land animals.", answer: true },
      { statement: "Dogs can fly naturally.", answer: false },
      { statement: "Fish live in water.", answer: true },
      { statement: "Cats bark.", answer: false },
      { statement: "Birds have feathers.", answer: true },
      { statement: "Snakes have legs.", answer: false },
      { statement: "Lions are carnivores.", answer: true },
      { statement: "Cows eat meat.", answer: false },
      { statement: "Frogs can live on land and water.", answer: true },
      { statement: "Penguins can fly.", answer: false },
    ],
    15: [
      { statement: "Mammals give birth to live young.", answer: true },
      { statement: "All animals have backbones.", answer: false },
      { statement: "Reptiles are cold-blooded.", answer: true },
      { statement: "Birds lay eggs.", answer: true },
      { statement: "Sharks are mammals.", answer: false },
      { statement: "Dolphins are mammals.", answer: true },
      { statement: "Insects have six legs.", answer: true },
      { statement: "Spiders have eight legs.", answer: true },
      { statement: "Amphibians can live in water and on land.", answer: true },
      { statement: "All animals are herbivores.", answer: false },
      { statement: "Tigers are herbivores.", answer: false },
      { statement: "Giraffes have long necks.", answer: true },
      { statement: "Bats are birds.", answer: false },
      { statement: "Whales breathe through gills.", answer: false },
      { statement: "Owls are nocturnal.", answer: true },
    ],
    20: [
      { statement: "Vertebrates have backbones.", answer: true },
      { statement: "Invertebrates have no backbones.", answer: true },
      { statement: "Fish breathe through gills.", answer: true },
      { statement: "Birds have fur.", answer: false },
      { statement: "Mammals produce milk.", answer: true },
      { statement: "Reptiles have scales.", answer: true },
      { statement: "Frogs are reptiles.", answer: false },
      { statement: "Snakes are reptiles.", answer: true },
      { statement: "Penguins are birds.", answer: true },
      { statement: "Ostriches can fly.", answer: false },
      { statement: "Cheetahs are the fastest land animals.", answer: true },
      { statement: "Elephants are herbivores.", answer: true },
      { statement: "Bears are omnivores.", answer: true },
      { statement: "Wolves hunt in packs.", answer: true },
      { statement: "Dolphins use echolocation.", answer: true },
      { statement: "Bats can see perfectly in the dark without sound.", answer: false },
      { statement: "Camels live in deserts.", answer: true },
      { statement: "Polar bears live in cold regions.", answer: true },
      { statement: "All animals live on land.", answer: false },
      { statement: "Some animals can camouflage.", answer: true },
    ],
    25: [
      { statement: "Herbivores eat plants.", answer: true },
      { statement: "Carnivores eat meat.", answer: true },
      { statement: "Omnivores eat both plants and animals.", answer: true },
      { statement: "Predators hunt other animals.", answer: true },
      { statement: "Prey hunts predators.", answer: false },
      { statement: "Migration is animal movement.", answer: true },
      { statement: "Hibernation is long sleep.", answer: true },
      { statement: "Camouflage helps animals hide.", answer: true },
      { statement: "Adaptation helps survival.", answer: true },
      { statement: "Habitat is where animals live.", answer: true },
      { statement: "Extinction means a species is gone.", answer: true },
      { statement: "Domestic animals are wild.", answer: false },
      { statement: "Wild animals live in nature.", answer: true },
      { statement: "Livestock are farm animals.", answer: true },
      { statement: "Pets are companion animals.", answer: true },
      { statement: "Endangered species are at risk.", answer: true },
      { statement: "Vertebrates include mammals.", answer: true },
      { statement: "Invertebrates include insects.", answer: true },
      { statement: "Amphibians include frogs.", answer: true },
      { statement: "Reptiles include snakes.", answer: true },
      { statement: "Mammals include humans.", answer: true },
      { statement: "Birds have feathers.", answer: true },
      { statement: "Fish live in water.", answer: true },
      { statement: "Insects have eight legs.", answer: false },
      { statement: "Arachnids have eight legs.", answer: true },
    ],
    30: [
      { statement: "Zoology is the study of animals.", answer: true },
      { statement: "Mammals are warm-blooded.", answer: true },
      { statement: "Reptiles are warm-blooded.", answer: false },
      { statement: "Birds are warm-blooded.", answer: true },
      { statement: "Fish are cold-blooded.", answer: true },
      { statement: "Amphibians start life in water.", answer: true },
      { statement: "Carnivores only eat plants.", answer: false },
      { statement: "Herbivores only eat plants.", answer: true },
      { statement: "Omnivores eat both.", answer: true },
      { statement: "Echolocation uses sound.", answer: true },
      { statement: "Pack behavior involves groups.", answer: true },
      { statement: "Territorial animals defend areas.", answer: true },
      { statement: "Mating is for reproduction.", answer: true },
      { statement: "Offspring are young animals.", answer: true },
      { statement: "Nests are animal homes.", answer: true },
      { statement: "Dens are shelters.", answer: true },
      { statement: "Burrows are underground homes.", answer: true },
      { statement: "Migration patterns are travel routes.", answer: true },
      { statement: "Food chains show feeding order.", answer: true },
      { statement: "Food webs are interconnected chains.", answer: true },
      { statement: "Keystone species are important to ecosystems.", answer: true },
      { statement: "Biodiversity means variety of life.", answer: true },
      { statement: "Ecosystems include living and non-living things.", answer: true },
      { statement: "Conservation protects animals.", answer: true },
      { statement: "Poaching is illegal hunting.", answer: true },
      { statement: "Wildlife reserves protect animals.", answer: true },
      { statement: "Zoos keep animals for viewing and care.", answer: true },
      { statement: "Aquariums house aquatic animals.", answer: true },
      { statement: "Domestication means taming animals.", answer: true },
      { statement: "Animals do not adapt to environments.", answer: false },
    ],
  },
  "Anime": {
    10: [
      { statement: "Naruto Uzumaki is a ninja.", answer: true },
      { statement: "Goku is from the anime One Piece.", answer: false },
      { statement: "Luffy wants to become Pirate King.", answer: true },
      { statement: "Pikachu is a Digimon.", answer: false },
      { statement: "Saitama defeats enemies with one punch.", answer: true },
      { statement: "Light Yagami uses a notebook to kill.", answer: true },
      { statement: "Ichigo Kurosaki is from Naruto.", answer: false },
      { statement: "Tanjiro is a demon.", answer: false },
      { statement: "Eren Yeager fights Titans.", answer: true },
      { statement: "Anime originated in Japan.", answer: true },
    ],
    15: [
      { statement: "Sasuke is Naruto’s rival.", answer: true },
      { statement: "Vegeta is stronger than Goku at all times.", answer: false },
      { statement: "Attack on Titan features giant humans.", answer: true },
      { statement: "Nezuko is Tanjiro’s sister.", answer: true },
      { statement: "Ash Ketchum trains Digimon.", answer: false },
      { statement: "Gojo is from Jujutsu Kaisen.", answer: true },
      { statement: "Asta uses magic naturally.", answer: false },
      { statement: "Deku is from My Hero Academia.", answer: true },
      { statement: "L is a detective.", answer: true },
      { statement: "Ryuk is a Shinigami.", answer: true },
      { statement: "Zoro uses three swords.", answer: true },
      { statement: "Naruto becomes Hokage.", answer: true },
      { statement: "Bleach is about pirates.", answer: false },
      { statement: "Fairy Tail is a guild.", answer: true },
      { statement: "Tokyo Ghoul features humans only.", answer: false },
    ],
    20: [
      { statement: "Goku is a Saiyan.", answer: true },
      { statement: "Luffy ate a Devil Fruit.", answer: true },
      { statement: "Levi is from Attack on Titan.", answer: true },
      { statement: "Saitama struggles to defeat enemies.", answer: false },
      { statement: "Edward Elric is an alchemist.", answer: true },
      { statement: "Alphonse Elric lost his body.", answer: true },
      { statement: "Natsu controls ice.", answer: false },
      { statement: "Erza is part of Fairy Tail.", answer: true },
      { statement: "Kaneki is a ghoul.", answer: true },
      { statement: "Aizen is a villain in Bleach.", answer: true },
      { statement: "Ichigo is a Soul Reaper.", answer: true },
      { statement: "Naruto belongs to the Uchiha clan.", answer: false },
      { statement: "Sasuke seeks revenge.", answer: true },
      { statement: "Gojo has powerful eyes.", answer: true },
      { statement: "Yuji Itadori hosts Sukuna.", answer: true },
      { statement: "Shinra controls fire.", answer: true },
      { statement: "Meliodas is a demon.", answer: true },
      { statement: "Ban is immortal.", answer: true },
      { statement: "Thorfinn is from Vinland Saga.", answer: true },
      { statement: "Anime always has happy endings.", answer: false },
    ],
    25: [
      { statement: "Luffy stretches because of his Devil Fruit.", answer: true },
      { statement: "Zoro is a swordsman.", answer: true },
      { statement: "Sanji is a cook.", answer: true },
      { statement: "Usopp is a sniper.", answer: true },
      { statement: "Gohan is Goku’s father.", answer: false },
      { statement: "Trunks is Vegeta’s son.", answer: true },
      { statement: "Frieza is a villain.", answer: true },
      { statement: "Cell is an android.", answer: true },
      { statement: "Deku has One For All.", answer: true },
      { statement: "Bakugo uses explosions.", answer: true },
      { statement: "Todoroki uses fire and ice.", answer: true },
      { statement: "All Might is a hero.", answer: true },
      { statement: "Kirito is from Sword Art Online.", answer: true },
      { statement: "Asuna is Kirito’s partner.", answer: true },
      { statement: "Lelouch has Geass power.", answer: true },
      { statement: "C.C. gives Lelouch power.", answer: true },
      { statement: "Spike Spiegel is a bounty hunter.", answer: true },
      { statement: "Vash is from Trigun.", answer: true },
      { statement: "Gintoki is serious all the time.", answer: false },
      { statement: "Yusuke is a spirit detective.", answer: true },
      { statement: "Hiei uses fire techniques.", answer: true },
      { statement: "Okabe is a scientist.", answer: true },
      { statement: "Subaru can return by death.", answer: true },
      { statement: "Emilia is a villain.", answer: false },
      { statement: "Koro-sensei is a teacher.", answer: true },
    ],
    30: [
      { statement: "Ace is Luffy’s brother.", answer: true },
      { statement: "Sabo is also Luffy’s brother.", answer: true },
      { statement: "Gol D. Roger was Pirate King.", answer: true },
      { statement: "Whitebeard was weak.", answer: false },
      { statement: "Denji turns into Chainsaw Man.", answer: true },
      { statement: "Power is a devil.", answer: true },
      { statement: "Makima is harmless.", answer: false },
      { statement: "Kagome is from Inuyasha.", answer: true },
      { statement: "Inuyasha is a full demon.", answer: false },
      { statement: "Kirito plays VR games.", answer: true },
      { statement: "Asuna is strong fighter.", answer: true },
      { statement: "Lelouch leads rebellion.", answer: true },
      { statement: "Suzaku is his friend and rival.", answer: true },
      { statement: "Spike flies a spaceship.", answer: true },
      { statement: "Jet Black is his partner.", answer: true },
      { statement: "Rimuru is a slime.", answer: true },
      { statement: "Shion works under Rimuru.", answer: true },
      { statement: "Subaru suffers repeatedly.", answer: true },
      { statement: "Rem is loyal to Subaru.", answer: true },
      { statement: "Karma is from Assassination Classroom.", answer: true },
      { statement: "Nagisa is the strongest physically.", answer: false },
      { statement: "Escanor grows stronger in sunlight.", answer: true },
      { statement: "Meliodas leads the Seven Deadly Sins.", answer: true },
      { statement: "Thorfinn seeks revenge.", answer: true },
      { statement: "Anime is only for kids.", answer: false },
      { statement: "Manga is printed comics.", answer: true },
      { statement: "Anime is always based on manga.", answer: false },
      { statement: "Voice actors are called seiyuu.", answer: true },
      { statement: "Anime includes many genres.", answer: true },
      { statement: "Japan is the origin of anime.", answer: true },
    ],
  },
  "Business": {
    10: [
      { statement: "A business sells goods or services.", answer: true },
      { statement: "Profit is the same as loss.", answer: false },
      { statement: "Customers buy products.", answer: true },
      { statement: "Revenue is total income.", answer: true },
      { statement: "Expenses are earnings.", answer: false },
      { statement: "Marketing promotes products.", answer: true },
      { statement: "A company is not a business.", answer: false },
      { statement: "Salary is payment to employees.", answer: true },
      { statement: "A product is always a service.", answer: false },
      { statement: "Services are intangible.", answer: true },
    ],
    15: [
      { statement: "Entrepreneurship means starting a business.", answer: true },
      { statement: "Capital is money used to start a business.", answer: true },
      { statement: "Investment guarantees profit.", answer: false },
      { statement: "A manager leads a team.", answer: true },
      { statement: "Employees own the company.", answer: false },
      { statement: "Supply is the amount of goods available.", answer: true },
      { statement: "Demand is the desire for goods.", answer: true },
      { statement: "Markets are places to buy and sell.", answer: true },
      { statement: "Competition helps businesses improve.", answer: true },
      { statement: "Branding identifies a product.", answer: true },
      { statement: "Advertising promotes products.", answer: true },
      { statement: "A logo represents a brand.", answer: true },
      { statement: "Wholesale sells directly to consumers only.", answer: false },
      { statement: "Retail sells to consumers.", answer: true },
      { statement: "Suppliers provide goods.", answer: true },
    ],
    20: [
      { statement: "Accounting tracks financial records.", answer: true },
      { statement: "Finance deals with money management.", answer: true },
      { statement: "A budget is a spending plan.", answer: true },
      { statement: "Loans must be repaid.", answer: true },
      { statement: "Interest is extra money paid on loans.", answer: true },
      { statement: "Banks store and manage money.", answer: true },
      { statement: "Savings means spending money.", answer: false },
      { statement: "Credit allows borrowing.", answer: true },
      { statement: "Debit increases account balance.", answer: false },
      { statement: "Transactions involve exchanges.", answer: true },
      { statement: "Invoices are bills.", answer: true },
      { statement: "Receipts prove payment.", answer: true },
      { statement: "Taxes are paid to government.", answer: true },
      { statement: "Insurance protects against risk.", answer: true },
      { statement: "Risk means guaranteed success.", answer: false },
      { statement: "Stocks represent ownership in a company.", answer: true },
      { statement: "Shareholders own shares.", answer: true },
      { statement: "Dividends are profit shares.", answer: true },
      { statement: "Mergers combine companies.", answer: true },
      { statement: "Acquisition means buying another company.", answer: true },
    ],
    25: [
      { statement: "Management organizes work.", answer: true },
      { statement: "Leadership involves guiding people.", answer: true },
      { statement: "HR stands for Human Resources.", answer: true },
      { statement: "Recruitment is hiring employees.", answer: true },
      { statement: "Training improves skills.", answer: true },
      { statement: "Productivity measures efficiency.", answer: true },
      { statement: "Quality refers to standards.", answer: true },
      { statement: "Customer service helps customers.", answer: true },
      { statement: "Negotiation reaches agreements.", answer: true },
      { statement: "Contracts are legal agreements.", answer: true },
      { statement: "Partnerships involve shared ownership.", answer: true },
      { statement: "Corporations are legal entities.", answer: true },
      { statement: "Sole proprietorship has one owner.", answer: true },
      { statement: "Franchising uses an existing brand.", answer: true },
      { statement: "Startups are new businesses.", answer: true },
      { statement: "Innovation means new ideas.", answer: true },
      { statement: "Strategy is a plan.", answer: true },
      { statement: "Mission defines purpose.", answer: true },
      { statement: "Vision shows future goals.", answer: true },
      { statement: "SWOT is an analysis tool.", answer: true },
      { statement: "Opportunities are risks only.", answer: false },
      { statement: "Threats are external risks.", answer: true },
      { statement: "Strengths are advantages.", answer: true },
      { statement: "Weaknesses are disadvantages.", answer: true },
      { statement: "KPIs measure performance.", answer: true },
    ],
    30: [
      { statement: "E-commerce is online business.", answer: true },
      { statement: "Digital marketing uses the internet.", answer: true },
      { statement: "Social media marketing promotes online.", answer: true },
      { statement: "SEO improves search visibility.", answer: true },
      { statement: "Content marketing uses content to promote.", answer: true },
      { statement: "Branding identity defines a brand image.", answer: true },
      { statement: "Customer loyalty means repeat buyers.", answer: true },
      { statement: "CRM manages customer relationships.", answer: true },
      { statement: "Supply chain moves products.", answer: true },
      { statement: "Logistics handles delivery of goods.", answer: true },
      { statement: "Inventory is stored goods.", answer: true },
      { statement: "Outsourcing hires external services.", answer: true },
      { statement: "Freelancing is independent work.", answer: true },
      { statement: "Passive income requires no effort at all.", answer: false },
      { statement: "Active income requires work.", answer: true },
      { statement: "Diversification spreads investments.", answer: true },
      { statement: "Monopoly has one seller.", answer: true },
      { statement: "Oligopoly has few sellers.", answer: true },
      { statement: "Market share is portion of market.", answer: true },
      { statement: "Break-even means no profit or loss.", answer: true },
      { statement: "ROI measures return on investment.", answer: true },
      { statement: "Cash flow tracks money movement.", answer: true },
      { statement: "Liquidity means easy to convert to cash.", answer: true },
      { statement: "Assets have value.", answer: true },
      { statement: "Liabilities are debts.", answer: true },
      { statement: "Equity is ownership value.", answer: true },
      { statement: "Audits review finances.", answer: true },
      { statement: "Compliance means following rules.", answer: true },
      { statement: "Business ethics involves moral principles.", answer: true },
      { statement: "Businesses do not need customers.", answer: false },
    ],
  },
  "Food": {
    10: [
      { statement: "Fruits are generally sweet.", answer: true },
      { statement: "Rice is a type of meat.", answer: false },
      { statement: "Milk is a dairy product.", answer: true },
      { statement: "Bread is made from flour.", answer: true },
      { statement: "Vegetables come from animals.", answer: false },
      { statement: "Sugar tastes salty.", answer: false },
      { statement: "Eggs are a source of protein.", answer: true },
      { statement: "Ice cream is served hot.", answer: false },
      { statement: "Water is essential for life.", answer: true },
      { statement: "Chocolate is made from cocoa beans.", answer: true },
    ],
    15: [
      { statement: "Pasta is made from wheat.", answer: true },
      { statement: "Cheese is made from milk.", answer: true },
      { statement: "A burger contains bread and meat.", answer: true },
      { statement: "Honey is made by bees.", answer: true },
      { statement: "Salt is sweet.", answer: false },
      { statement: "Juice is made from fruits.", answer: true },
      { statement: "Vegetables are always cooked before eating.", answer: false },
      { statement: "Soup is usually liquid.", answer: true },
      { statement: "Tea is made from leaves.", answer: true },
      { statement: "Coffee is made from beans.", answer: true },
      { statement: "A sandwich has filling between bread.", answer: true },
      { statement: "Tofu is made from soybeans.", answer: true },
      { statement: "Butter is made from plants only.", answer: false },
      { statement: "Fruits contain vitamins.", answer: true },
      { statement: "Junk food is always healthy.", answer: false },
    ],
    20: [
      { statement: "Rice is a staple food in many countries.", answer: true },
      { statement: "Chicken is a type of meat.", answer: true },
      { statement: "Fish live on land.", answer: false },
      { statement: "Eggs can be boiled or fried.", answer: true },
      { statement: "Yogurt is a dairy product.", answer: true },
      { statement: "Cereal is eaten for breakfast.", answer: true },
      { statement: "Soda is a healthy drink.", answer: false },
      { statement: "Tea contains caffeine.", answer: true },
      { statement: "Steak comes from plants.", answer: false },
      { statement: "Bread is baked.", answer: true },
      { statement: "Salad contains vegetables.", answer: true },
      { statement: "Cake is a dessert.", answer: true },
      { statement: "Chocolate is bitter by nature.", answer: true },
      { statement: "Sugar is a sweetener.", answer: true },
      { statement: "Salt enhances flavor.", answer: true },
      { statement: "Fruits grow on trees or plants.", answer: true },
      { statement: "Meat comes from animals.", answer: true },
      { statement: "Ice cream melts in heat.", answer: true },
      { statement: "Soup is always cold.", answer: false },
      { statement: "Cooking changes food texture.", answer: true },
    ],
    25: [
      { statement: "Frying uses oil.", answer: true },
      { statement: "Boiling uses water.", answer: true },
      { statement: "Baking uses an oven.", answer: true },
      { statement: "Grilling uses direct heat.", answer: true },
      { statement: "Steaming uses vapor.", answer: true },
      { statement: "A chef cooks food professionally.", answer: true },
      { statement: "A kitchen is used for sleeping.", answer: false },
      { statement: "A menu lists food items.", answer: true },
      { statement: "Restaurants serve food.", answer: true },
      { statement: "Fast food is usually quick to prepare.", answer: true },
      { statement: "Organic food is natural.", answer: true },
      { statement: "Junk food is nutritious.", answer: false },
      { statement: "A beverage is a drink.", answer: true },
      { statement: "Snacks are large meals.", answer: false },
      { statement: "Breakfast is eaten in the morning.", answer: true },
      { statement: "Lunch is eaten at night.", answer: false },
      { statement: "Dinner is usually in the evening.", answer: true },
      { statement: "Appetizers are served first.", answer: true },
      { statement: "Main course is the primary dish.", answer: true },
      { statement: "Dessert is usually sweet.", answer: true },
      { statement: "Spices add flavor.", answer: true },
      { statement: "Herbs come from plants.", answer: true },
      { statement: "Ingredients are parts of a recipe.", answer: true },
      { statement: "Cooking means preparing food.", answer: true },
      { statement: "Food cannot spoil.", answer: false },
    ],
    30: [
      { statement: "A diet is what a person eats regularly.", answer: true },
      { statement: "Nutrition is related to food and health.", answer: true },
      { statement: "Protein helps build muscles.", answer: true },
      { statement: "Carbohydrates provide energy.", answer: true },
      { statement: "Fats are useless to the body.", answer: false },
      { statement: "Vitamins are essential nutrients.", answer: true },
      { statement: "Minerals support body functions.", answer: true },
      { statement: "Fiber helps digestion.", answer: true },
      { statement: "Calories measure energy.", answer: true },
      { statement: "A balanced diet is unhealthy.", answer: false },
      { statement: "Vegetarians eat meat.", answer: false },
      { statement: "Vegans avoid animal products.", answer: true },
      { statement: "Gluten is found in wheat.", answer: true },
      { statement: "Lactose is found in milk.", answer: true },
      { statement: "Cholesterol is always harmful.", answer: false },
      { statement: "Sodium is found in salt.", answer: true },
      { statement: "Potassium is a mineral.", answer: true },
      { statement: "Hydration means drinking enough water.", answer: true },
      { statement: "Digestion breaks down food.", answer: true },
      { statement: "Metabolism processes energy.", answer: true },
      { statement: "Food allergies can be dangerous.", answer: true },
      { statement: "Processed food is always fresh.", answer: false },
      { statement: "Raw food is uncooked.", answer: true },
      { statement: "Frozen food is preserved.", answer: true },
      { statement: "Canned food is stored in containers.", answer: true },
      { statement: "Expiration dates indicate safety.", answer: true },
      { statement: "Serving size shows portion amount.", answer: true },
      { statement: "Portion control helps health.", answer: true },
      { statement: "Food never expires.", answer: false },
      { statement: "Healthy eating supports the body.", answer: true },
    ],
  },
  "History": {
    10: [
      { statement: "World War II ended in 1945.", answer: true },
      { statement: "The Roman Empire started in Asia.", answer: false },
      { statement: "Christopher Columbus discovered America in 1492.", answer: true },
      { statement: "The Great Wall of China is in Japan.", answer: false },
      { statement: "Ancient Egypt was along the Nile River.", answer: true },
      { statement: "The Philippines was colonized by Spain.", answer: true },
      { statement: "World War I happened after World War II.", answer: false },
      { statement: "Jose Rizal is a Philippine national hero.", answer: true },
      { statement: "The Industrial Revolution started in France.", answer: false },
      { statement: "The pyramids are located in Egypt.", answer: true },
    ],
    15: [
      { statement: "Napoleon was from France.", answer: true },
      { statement: "The Cold War involved direct fighting between USA and USSR.", answer: false },
      { statement: "Ferdinand Magellan reached the Philippines.", answer: true },
      { statement: "The Declaration of Independence was signed in 1776.", answer: true },
      { statement: "The Berlin Wall divided Germany.", answer: true },
      { statement: "The Titanic sank in 1912.", answer: true },
      { statement: "Ancient Greece influenced democracy.", answer: true },
      { statement: "The printing press was invented by Einstein.", answer: false },
      { statement: "WWI started in 1914.", answer: true },
      { statement: "The Middle Ages came after the Renaissance.", answer: false },
      { statement: "Julius Caesar was a Roman leader.", answer: true },
      { statement: "The Eiffel Tower is in London.", answer: false },
      { statement: "The American Civil War was in the USA.", answer: true },
      { statement: "The first humans lived in Africa.", answer: true },
      { statement: "The moon landing happened in 1969.", answer: true },
    ],
    20: [
      { statement: "The Stone Age came before the Iron Age.", answer: true },
      { statement: "Cleopatra was Egyptian.", answer: true },
      { statement: "The Vikings came from Spain.", answer: false },
      { statement: "The Ottoman Empire existed for centuries.", answer: true },
      { statement: "World War II involved nuclear weapons.", answer: true },
      { statement: "Adolf Hitler was a US president.", answer: false },
      { statement: "The Renaissance was a cultural movement.", answer: true },
      { statement: "The first Olympics were in Greece.", answer: true },
      { statement: "The Great Depression was an economic crisis.", answer: true },
      { statement: "The Philippines gained independence in 1946.", answer: true },
      { statement: "The Spanish Armada invaded England.", answer: true },
      { statement: "The French Revolution started in 1789.", answer: true },
      { statement: "The Black Death was a disease outbreak.", answer: true },
      { statement: "Christopher Columbus was Italian.", answer: true },
      { statement: "The Cold War lasted until 1991.", answer: true },
      { statement: "The Statue of Liberty is in Canada.", answer: false },
      { statement: "World War I ended in 1918.", answer: true },
      { statement: "The Aztecs were in South America.", answer: false },
      { statement: "The Inca Empire was in Peru.", answer: true },
      { statement: "Ancient Rome used aqueducts.", answer: true },
    ],
    25: [
      { statement: "The first president of the USA was George Washington.", answer: true },
      { statement: "The Magna Carta was signed in England.", answer: true },
      { statement: "The Berlin Wall fell in 1989.", answer: true },
      { statement: "The Industrial Revolution started in Britain.", answer: true },
      { statement: "The Great Wall of China is visible from space easily.", answer: false },
      { statement: "World War II had two main sides.", answer: true },
      { statement: "The Roman Empire fell in 476 AD.", answer: true },
      { statement: "The Cold War was between USA and USSR.", answer: true },
      { statement: "The French Revolution ended monarchy in France.", answer: true },
      { statement: "The printing press changed history.", answer: true },
      { statement: "Marco Polo traveled to Asia.", answer: true },
      { statement: "The Renaissance began in Europe.", answer: true },
      { statement: "The Black Death killed millions.", answer: true },
      { statement: "The Titanic was a ship.", answer: true },
      { statement: "The first humans used smartphones.", answer: false },
      { statement: "The pyramids are ancient structures.", answer: true },
      { statement: "Julius Caesar was assassinated.", answer: true },
      { statement: "The USA gained independence from Britain.", answer: true },
      { statement: "World War I used tanks.", answer: true },
      { statement: "The Cold War involved nuclear tension.", answer: true },
      { statement: "The Vikings were explorers.", answer: true },
      { statement: "The Aztecs had a written language.", answer: true },
      { statement: "The Renaissance focused on art and science.", answer: true },
      { statement: "Napoleon was defeated at Waterloo.", answer: true },
      { statement: "The Industrial Revolution increased factory work.", answer: true },
    ],
    30: [
      { statement: "Ancient humans used stone tools.", answer: true },
      { statement: "The first civilization was in Mesopotamia.", answer: true },
      { statement: "The Roman Empire was in Europe.", answer: true },
      { statement: "The Great Wall was built overnight.", answer: false },
      { statement: "World War II ended in 1945.", answer: true },
      { statement: "The Cold War was a hot war.", answer: false },
      { statement: "The Renaissance means rebirth.", answer: true },
      { statement: "The Middle Ages were before modern times.", answer: true },
      { statement: "Christopher Columbus reached Asia.", answer: false },
      { statement: "Ferdinand Magellan died in the Philippines.", answer: true },
      { statement: "The American Revolution was in the 1700s.", answer: true },
      { statement: "The Industrial Revolution started in the 1900s.", answer: false },
      { statement: "Ancient Egyptians built pyramids.", answer: true },
      { statement: "The Vikings were from Scandinavia.", answer: true },
      { statement: "The Black Death was a plague.", answer: true },
      { statement: "The Berlin Wall divided East and West Germany.", answer: true },
      { statement: "The Cold War ended in 1991.", answer: true },
      { statement: "The printing press helped spread knowledge.", answer: true },
      { statement: "The Roman Empire had emperors.", answer: true },
      { statement: "Julius Caesar was a dictator.", answer: true },
      { statement: "The USA has always been independent.", answer: false },
      { statement: "The French Revolution changed France.", answer: true },
      { statement: "The Industrial Revolution introduced machines.", answer: true },
      { statement: "The first humans lived in cities.", answer: false },
      { statement: "Ancient Greece influenced modern democracy.", answer: true },
      { statement: "The Ottoman Empire was in Europe and Asia.", answer: true },
      { statement: "World War I started in 1914.", answer: true },
      { statement: "World War II involved the Axis powers.", answer: true },
      { statement: "The Titanic sank after hitting an iceberg.", answer: true },
      { statement: "History is the study of the past.", answer: true },
    ],
  },
  "Nature": {
    10: [
      { statement: "Trees produce oxygen.", answer: true },
      { statement: "Rivers flow uphill.", answer: false },
      { statement: "Rain comes from clouds.", answer: true },
      { statement: "Deserts are always cold.", answer: false },
      { statement: "Plants need sunlight to survive.", answer: true },
      { statement: "The ocean is freshwater.", answer: false },
      { statement: "Soil contains nutrients.", answer: true },
      { statement: "Volcanoes can erupt lava.", answer: true },
      { statement: "Wind is moving air.", answer: true },
      { statement: "Snow is liquid water.", answer: false },
    ],
    15: [
      { statement: "The rainforest has many animals.", answer: true },
      { statement: "All plants are green.", answer: false },
      { statement: "Mountains are flat.", answer: false },
      { statement: "Lakes are smaller than oceans.", answer: true },
      { statement: "A valley is low land between hills.", answer: true },
      { statement: "Earthquakes can shake the ground.", answer: true },
      { statement: "Lightning is hotter than the sun’s surface.", answer: true },
      { statement: "Clouds are made of smoke.", answer: false },
      { statement: "Water cycle includes evaporation.", answer: true },
      { statement: "Oceans cover most of Earth.", answer: true },
      { statement: "Sand is found in deserts.", answer: true },
      { statement: "All deserts are sandy.", answer: false },
      { statement: "Plants can grow without water.", answer: false },
      { statement: "The atmosphere protects Earth.", answer: true },
      { statement: "Hurricanes are calm weather events.", answer: false },
    ],
    20: [
      { statement: "The Earth has four seasons.", answer: true },
      { statement: "Spring comes after winter.", answer: true },
      { statement: "The equator is the coldest part of Earth.", answer: false },
      { statement: "Glaciers are made of ice.", answer: true },
      { statement: "The ozone layer protects from UV rays.", answer: true },
      { statement: "Rivers flow to the sea.", answer: true },
      { statement: "A forest has many trees.", answer: true },
      { statement: "Grasslands have no plants.", answer: false },
      { statement: "Coral reefs are underwater ecosystems.", answer: true },
      { statement: "Pollution harms the environment.", answer: true },
      { statement: "Recycling helps nature.", answer: true },
      { statement: "Animals live only on land.", answer: false },
      { statement: "The Sahara is a desert.", answer: true },
      { statement: "Antarctica is a desert.", answer: true },
      { statement: "Fog is a type of cloud near ground.", answer: true },
      { statement: "Tornadoes are harmless.", answer: false },
      { statement: "Earth has one natural satellite.", answer: true },
      { statement: "The moon affects tides.", answer: true },
      { statement: "Rivers can dry up.", answer: true },
      { statement: "Volcanoes only exist underwater.", answer: false },
    ],
    25: [
      { statement: "Ecosystems include living and non-living things.", answer: true },
      { statement: "Food chains show energy flow.", answer: true },
      { statement: "Predators eat plants only.", answer: false },
      { statement: "Herbivores eat plants.", answer: true },
      { statement: "Carnivores eat meat.", answer: true },
      { statement: "Omnivores eat both plants and animals.", answer: true },
      { statement: "Biodiversity means variety of life.", answer: true },
      { statement: "Deforestation helps the environment.", answer: false },
      { statement: "Climate change affects weather.", answer: true },
      { statement: "Pollution improves air quality.", answer: false },
      { statement: "Recycling reduces waste.", answer: true },
      { statement: "Oxygen is harmful to humans.", answer: false },
      { statement: "Carbon dioxide is used by plants.", answer: true },
      { statement: "Trees help reduce pollution.", answer: true },
      { statement: "Wetlands store water.", answer: true },
      { statement: "Coral reefs support marine life.", answer: true },
      { statement: "Ice caps are melting due to warming.", answer: true },
      { statement: "Nature is unaffected by humans.", answer: false },
      { statement: "Renewable energy comes from nature.", answer: true },
      { statement: "Fossil fuels are renewable.", answer: false },
      { statement: "Wind is a renewable energy source.", answer: true },
      { statement: "Solar energy comes from the sun.", answer: true },
      { statement: "Rivers never change course.", answer: false },
      { statement: "Soil erosion can happen naturally.", answer: true },
      { statement: "Ecosystems can be damaged.", answer: true },
    ],
    30: [
      { statement: "The biosphere includes all living things.", answer: true },
      { statement: "The hydrosphere is all water on Earth.", answer: true },
      { statement: "The atmosphere is made of gases.", answer: true },
      { statement: "Earth has only one climate zone.", answer: false },
      { statement: "Tropical regions are near the equator.", answer: true },
      { statement: "Polar regions are always hot.", answer: false },
      { statement: "Seasons are caused by Earth’s tilt.", answer: true },
      { statement: "The water cycle never stops.", answer: true },
      { statement: "Evaporation turns water into gas.", answer: true },
      { statement: "Condensation forms clouds.", answer: true },
      { statement: "Precipitation includes rain and snow.", answer: true },
      { statement: "Rivers flow from oceans to mountains.", answer: false },
      { statement: "Lakes are surrounded by land.", answer: true },
      { statement: "Mountains are formed by tectonic plates.", answer: true },
      { statement: "Earthquakes happen due to plate movement.", answer: true },
      { statement: "Volcanoes release lava.", answer: true },
      { statement: "Tsunamis are caused by underwater earthquakes.", answer: true },
      { statement: "Hurricanes form over warm oceans.", answer: true },
      { statement: "Tornadoes are weaker than hurricanes.", answer: false },
      { statement: "Weather changes daily.", answer: true },
      { statement: "Climate is long-term weather pattern.", answer: true },
      { statement: "Rainforests have high rainfall.", answer: true },
      { statement: "Deserts receive very little rain.", answer: true },
      { statement: "Grasslands are full of trees.", answer: false },
      { statement: "Tundra is very cold.", answer: true },
      { statement: "Animals depend on ecosystems.", answer: true },
      { statement: "Plants do not need sunlight.", answer: false },
      { statement: "Oxygen is part of air.", answer: true },
      { statement: "Air pollution affects health.", answer: true },
      { statement: "Nature is independent of humans.", answer: false },
    ],
  },
  "Science": {
    10: [
      { statement: "The Earth revolves around the Sun.", answer: true },
      { statement: "Water boils at 50°C.", answer: false },
      { statement: "Plants produce oxygen.", answer: true },
      { statement: "Humans breathe carbon dioxide.", answer: false },
      { statement: "The Sun is a star.", answer: true },
      { statement: "Gravity pushes objects away from Earth.", answer: false },
      { statement: "The human body has 206 bones.", answer: true },
      { statement: "Sound travels faster than light.", answer: false },
      { statement: "The heart pumps blood.", answer: true },
      { statement: "Ice is hotter than steam.", answer: false },
    ],
    15: [
      { statement: "The Moon produces its own light.", answer: false },
      { statement: "Electricity can flow through metals.", answer: true },
      { statement: "Humans have five senses.", answer: true },
      { statement: "Air has no weight.", answer: false },
      { statement: "The Earth is flat.", answer: false },
      { statement: "Plants need sunlight to grow.", answer: true },
      { statement: "DNA is found in cells.", answer: true },
      { statement: "The liver pumps blood.", answer: false },
      { statement: "Sound needs a medium to travel.", answer: true },
      { statement: "Water is made of hydrogen and oxygen.", answer: true },
      { statement: "The brain controls the body.", answer: true },
      { statement: "Fish can breathe air like humans.", answer: false },
      { statement: "Heat flows from cold to hot.", answer: false },
      { statement: "Energy cannot be created or destroyed.", answer: true },
      { statement: "The Sun orbits the Earth.", answer: false },
    ],
    20: [
      { statement: "Light travels in waves.", answer: true },
      { statement: "The human body has four lungs.", answer: false },
      { statement: "The atom is the smallest unit of matter.", answer: true },
      { statement: "Plants use photosynthesis.", answer: true },
      { statement: "The Earth has two moons.", answer: false },
      { statement: "Oxygen is needed for breathing.", answer: true },
      { statement: "The skeleton supports the body.", answer: true },
      { statement: "Metals are poor conductors.", answer: false },
      { statement: "The Sun is a planet.", answer: false },
      { statement: "Water freezes at 0°C.", answer: true },
      { statement: "Humans have three hearts.", answer: false },
      { statement: "Sound travels in a vacuum.", answer: false },
      { statement: "The eye helps us see.", answer: true },
      { statement: "The brain is part of the nervous system.", answer: true },
      { statement: "Electricity is a form of energy.", answer: true },
      { statement: "The Earth rotates on its axis.", answer: true },
      { statement: "Heat is a type of energy.", answer: true },
      { statement: "Plants only produce carbon dioxide.", answer: false },
      { statement: "The Moon affects tides.", answer: true },
      { statement: "Gravity exists only on Earth.", answer: false },
    ],
    25: [
      { statement: "Cells are the basic units of life.", answer: true },
      { statement: "The human heart has two chambers.", answer: false },
      { statement: "Water expands when frozen.", answer: true },
      { statement: "The Sun is larger than Earth.", answer: true },
      { statement: "Sound travels faster in water than air.", answer: true },
      { statement: "Humans can survive without oxygen.", answer: false },
      { statement: "The stomach digests food.", answer: true },
      { statement: "The Earth is the center of the universe.", answer: false },
      { statement: "Light travels faster than sound.", answer: true },
      { statement: "Plants absorb carbon dioxide.", answer: true },
      { statement: "The human body has one brain.", answer: true },
      { statement: "The lungs help in breathing.", answer: true },
      { statement: "Water has no taste.", answer: true },
      { statement: "The Sun is made mostly of hydrogen.", answer: true },
      { statement: "Ice sinks in water.", answer: false },
      { statement: "Blood carries oxygen.", answer: true },
      { statement: "The Earth has one sun.", answer: true },
      { statement: "Animals make their own food.", answer: false },
      { statement: "The heart is a muscle.", answer: true },
      { statement: "The eye can hear sounds.", answer: false },
      { statement: "The ear helps in balance.", answer: true },
      { statement: "Gravity affects all objects with mass.", answer: true },
      { statement: "Sound is a form of energy.", answer: true },
      { statement: "The brain controls thoughts.", answer: true },
      { statement: "Water is a solid at room temperature.", answer: false },
    ],
    30: [
      { statement: "The Earth revolves around the Moon.", answer: false },
      { statement: "Plants release oxygen during photosynthesis.", answer: true },
      { statement: "The Sun is a source of energy.", answer: true },
      { statement: "Humans have gills.", answer: false },
      { statement: "The brain sends signals through nerves.", answer: true },
      { statement: "The skeleton protects organs.", answer: true },
      { statement: "Sound travels fastest in solids.", answer: true },
      { statement: "Water boils at 100°C.", answer: true },
      { statement: "Metals expand when heated.", answer: true },
      { statement: "The Moon has its own light.", answer: false },
      { statement: "The Earth has gravity.", answer: true },
      { statement: "Air contains oxygen.", answer: true },
      { statement: "Fish breathe using lungs.", answer: false },
      { statement: "Energy can be destroyed.", answer: false },
      { statement: "The human body needs water.", answer: true },
      { statement: "Light travels faster than sound.", answer: true },
      { statement: "The heart pumps blood throughout the body.", answer: true },
      { statement: "Plants grow without water.", answer: false },
      { statement: "The Earth is spherical.", answer: true },
      { statement: "Electricity flows through plastic easily.", answer: false },
      { statement: "The Sun is closer than other stars.", answer: true },
      { statement: "The eye detects light.", answer: true },
      { statement: "The ear detects sound.", answer: true },
      { statement: "The skin protects the body.", answer: true },
      { statement: "Oxygen is harmful to humans.", answer: false },
      { statement: "The liver helps detoxify the body.", answer: true },
      { statement: "The kidney filters blood.", answer: true },
      { statement: "The stomach stores food.", answer: true },
      { statement: "The brain is inside the skull.", answer: true },
      { statement: "The Earth is the hottest planet.", answer: false },
    ],
  },
  "Tech": {
    10: [
      { statement: "Computers process data using binary.", answer: true },
      { statement: "The internet was invented in 2020.", answer: false },
      { statement: "A smartphone is a type of computer.", answer: true },
      { statement: "Wi-Fi uses cables to connect devices.", answer: false },
      { statement: "Software refers to physical parts of a computer.", answer: false },
      { statement: "Hardware refers to physical components.", answer: true },
      { statement: "Google is a search engine.", answer: true },
      { statement: "HTML is a programming language.", answer: false },
      { statement: "RAM stores data permanently.", answer: false },
      { statement: "A CPU is the brain of the computer.", answer: true },
    ],
    15: [
      { statement: "Python is a programming language.", answer: true },
      { statement: "Microsoft Word is a video game.", answer: false },
      { statement: "Cybersecurity protects systems from attacks.", answer: true },
      { statement: "Bluetooth works over short distances.", answer: true },
      { statement: "Artificial Intelligence can learn patterns.", answer: true },
      { statement: "A mouse is an input device.", answer: true },
      { statement: "A monitor is an input device.", answer: false },
      { statement: "Data can be stored in the cloud.", answer: true },
      { statement: "Email was invented before computers.", answer: false },
      { statement: "Operating systems manage computer hardware.", answer: true },
      { statement: "Linux is an operating system.", answer: true },
      { statement: "Smartphones cannot connect to the internet.", answer: false },
      { statement: "USB stands for Universal Serial Bus.", answer: true },
      { statement: "A keyboard is used for typing input.", answer: true },
      { statement: "A printer is an output device.", answer: true },
    ],
    20: [
      { statement: "The first computer was very small.", answer: false },
      { statement: "Supercomputers are very powerful.", answer: true },
      { statement: "Cloud storage requires internet.", answer: true },
      { statement: "Antivirus software protects computers.", answer: true },
      { statement: "A firewall blocks unwanted access.", answer: true },
      { statement: "HTML is used for creating websites.", answer: true },
      { statement: "CSS is used for styling websites.", answer: true },
      { statement: "JavaScript makes websites interactive.", answer: true },
      { statement: "A database stores information.", answer: true },
      { statement: "A router connects networks.", answer: true },
      { statement: "A modem connects to the internet.", answer: true },
      { statement: "AI means Artificial Intelligence.", answer: true },
      { statement: "Robots always look like humans.", answer: false },
      { statement: "Machines can replace all human jobs.", answer: false },
      { statement: "The internet is a global network.", answer: true },
      { statement: "Social media is a form of technology.", answer: true },
      { statement: "Gaming consoles are computers.", answer: true },
      { statement: "Laptops are portable computers.", answer: true },
      { statement: "Tablets are larger than laptops.", answer: false },
      { statement: "Technology only includes computers.", answer: false },
    ],
    25: [
      { statement: "Machine learning is part of AI.", answer: true },
      { statement: "Deep learning uses neural networks.", answer: true },
      { statement: "Big data refers to large datasets.", answer: true },
      { statement: "Encryption protects data.", answer: true },
      { statement: "Hackers always do illegal activities.", answer: false },
      { statement: "Open-source software is free to modify.", answer: true },
      { statement: "Android is an operating system.", answer: true },
      { statement: "iOS is used in Apple devices.", answer: true },
      { statement: "Smartphones use apps.", answer: true },
      { statement: "Apps are software programs.", answer: true },
      { statement: "HTML builds structure of websites.", answer: true },
      { statement: "CSS adds style to websites.", answer: true },
      { statement: "Java is only used for coffee.", answer: false },
      { statement: "Cloud computing stores data online.", answer: true },
      { statement: "Cybercrime involves illegal online activity.", answer: true },
      { statement: "VPN hides user location.", answer: true },
      { statement: "Blockchain is used in cryptocurrency.", answer: true },
      { statement: "Bitcoin is a type of technology.", answer: true },
      { statement: "Servers store and deliver data.", answer: true },
      { statement: "Websites run on servers.", answer: true },
      { statement: "URLs are web addresses.", answer: true },
      { statement: "HTTP is used for websites.", answer: true },
      { statement: "HTTPS is more secure than HTTP.", answer: true },
      { statement: "Cookies store browsing data.", answer: true },
      { statement: "Browsers are used to access the internet.", answer: true },
    ],
    30: [
      { statement: "Quantum computers are widely used today.", answer: false },
      { statement: "AI can recognize images.", answer: true },
      { statement: "Self-driving cars use technology.", answer: true },
      { statement: "Drones are unmanned devices.", answer: true },
      { statement: "5G is faster than 4G.", answer: true },
      { statement: "Wi-Fi stands for Wireless Fidelity.", answer: true },
      { statement: "Bluetooth is a type of internet.", answer: false },
      { statement: "A laptop is a portable computer.", answer: true },
      { statement: "A desktop computer is not portable.", answer: true },
      { statement: "Malware is harmful software.", answer: true },
      { statement: "A virus is a type of malware.", answer: true },
      { statement: "Spyware steals information.", answer: true },
      { statement: "Phishing is a cyber attack.", answer: true },
      { statement: "Cloud computing uses physical storage only.", answer: false },
      { statement: "Data science involves analyzing data.", answer: true },
      { statement: "Programming languages include Python.", answer: true },
      { statement: "JavaScript is used for web development.", answer: true },
      { statement: "Operating systems manage hardware.", answer: true },
      { statement: "A GPU processes graphics.", answer: true },
      { statement: "A CPU handles general processing.", answer: true },
      { statement: "SSD is faster than HDD.", answer: true },
      { statement: "USB-C is a type of connector.", answer: true },
      { statement: "QR codes store data visually.", answer: true },
      { statement: "Virtual reality is a simulation technology.", answer: true },
      { statement: "Augmented reality adds digital elements.", answer: true },
      { statement: "Robots can perform tasks automatically.", answer: true },
      { statement: "AI always thinks like humans.", answer: false },
      { statement: "The internet is controlled by one country.", answer: false },
      { statement: "Software updates improve performance.", answer: true },
      { statement: "Technology is always digital.", answer: false },
    ],
  },
};

export const getTrueFalseBankQuestions = (category: string, count: number): PreparedTrueFalseQuestion[] => {
  const byCategory = trueFalseQuestionBank[category];
  if (!byCategory) return [];
  const entries = byCategory[count as TrueFalseQuestionCount] ?? [];
  return entries.map((entry) => ({
    question: entry.statement,
    options: ["True", "False"],
    correctAnswer: entry.answer ? "True" : "False",
  }));
};
